### PR TITLE
Almost there!

### PR DESCRIPTION
**Pull request by ZachariasOctavious**
This build has everything from the tutorial to the store to the leaderboards.

### CODE REVIEW

**Comment by Mr-Coxall** [comment]
Any chance you could commit to Github?

**Comment by ZachariasOctavious** [comment]
Hi sir,

In regard to your comment on Github, I was a little confused by what you
meant. I have committed the most recent version that I have to Github and
made a pull request. Let me know what else I need to do.

Thanks.
On Jan 9, 2016 2:58 PM, "Mr. Coxall" <notifications@github.com> wrote:

> Any chance you could commit to Github?
>
> > On Jan 8, 2016, at 5:32 PM, Zacharias <notifications@github.com> wrote:
> >
> > This build has everything from the tutorial to the store to the
> leaderboards.
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7
> >
> > Commit Summary
> >
> > added skip scene and background previews scene
> > fixed equation bug, added in leaderboards code, changed the display time
> for the company and game logo, completed credits, tutorial completed
> > File Changes
> >
> > M Icon.png (0)
> > M Info.plist (7)
> > M tabs/AchievementsScene.lua (20)
> > A tabs/BackgroundPreviewScene.lua (49)
> > M tabs/CompanyLogoScene.lua (2)
> > M tabs/CreditsScene.lua (52)
> > M tabs/GameLogoScene.lua (10)
> > M tabs/HelperClass.lua (90)
> > A tabs/LeaderboardsScene.lua (36)
> > M tabs/LevelDifficultyScene.lua (7)
> > M tabs/Main.lua (19)
> > M tabs/MainGameRight.lua (7)
> > M tabs/MainGameScene.lua (27)
> > A tabs/MainGameSkipScene.lua (48)
> > M tabs/MainGameTotalScoreScene.lua (6)
> > M tabs/MainGameWrong.lua (14)
> > M tabs/MainMenuScene.lua (18)
> > M tabs/SettingsScene.lua (8)
> > M tabs/StoreScene.lua (65)
> > M tabs/TutorialLevelDifficultyScene.lua (2)
> > M tabs/TutorialMainGameRightScene.lua (22)
> > M tabs/TutorialMainGameScene.lua (60)
> > A tabs/TutorialMainGameWrongScene.lua (44)
> > M tabs/TutorialMainMenuScene.lua (10)
> > A tabs/TutorialOverScene.lua (39)
> > M tabs/WorldsScene.lua (6)
> > Patch Links:
> >
> > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7.patch
> > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7.diff
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7#issuecomment-170274879>
> .
>

-- 
*ocsb.ca 
<http://ocsb.ca/?utm_source=ocsbstudents&utm_medium=email_footer&utm_campaign=awareness> *
| *Inspired education. Inspiring students.* 

Think "green," please consider the environment before printing this email.


*Confidentiality and privacy notice: This email, including any attachments, 
is for the sole use of the intended recipient(s) and may contain 
confidential and privileged information. Any unauthorized review, use, 
disclosure, or distribution is prohibited. If you received this email 
and are not the intended recipient, please inform the sender by email reply 
and destroy all copies of the original message. This email and any 
emails sent to or from the Ottawa Catholic School Board may be 
transmitted or stored outside of Canada. *

**Comment by Mr-Coxall** [comment]
That is what I meant. 
Just wanted to make sure we had a backup on GitHub.

**Comment by ZachariasOctavious** [comment]
Thanks for clearing it up. I've added the game center code into the project
and the backup on Github has it and I'm currently working on fixing those
bugs you listed on the board.

Have a nice weekend.
On Jan 9, 2016 6:31 PM, "Mr. Coxall" <notifications@github.com> wrote:

> That is what I meant.
> Just wanted to make sure we had a backup on GitHub.
>
> > On Jan 9, 2016, at 5:40 PM, Zacharias <notifications@github.com> wrote:
> >
> > Hi sir,
> >
> > In regard to your comment on Github, I was a little confused by what you
> > meant. I have committed the most recent version that I have to Github and
> > made a pull request. Let me know what else I need to do.
> >
> > Thanks.
> > On Jan 9, 2016 2:58 PM, "Mr. Coxall" <notifications@github.com> wrote:
> >
> > > Any chance you could commit to Github?
> > >
> > > > On Jan 8, 2016, at 5:32 PM, Zacharias <notifications@github.com>
> wrote:
> > > >
> > > > This build has everything from the tutorial to the store to the
> > > leaderboards.
> > > >
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7
> > > >
> > > > Commit Summary
> > > >
> > > > added skip scene and background previews scene
> > > > fixed equation bug, added in leaderboards code, changed the display
> time
> > > for the company and game logo, completed credits, tutorial completed
> > > > File Changes
> > > >
> > > > M Icon.png (0)
> > > > M Info.plist (7)
> > > > M tabs/AchievementsScene.lua (20)
> > > > A tabs/BackgroundPreviewScene.lua (49)
> > > > M tabs/CompanyLogoScene.lua (2)
> > > > M tabs/CreditsScene.lua (52)
> > > > M tabs/GameLogoScene.lua (10)
> > > > M tabs/HelperClass.lua (90)
> > > > A tabs/LeaderboardsScene.lua (36)
> > > > M tabs/LevelDifficultyScene.lua (7)
> > > > M tabs/Main.lua (19)
> > > > M tabs/MainGameRight.lua (7)
> > > > M tabs/MainGameScene.lua (27)
> > > > A tabs/MainGameSkipScene.lua (48)
> > > > M tabs/MainGameTotalScoreScene.lua (6)
> > > > M tabs/MainGameWrong.lua (14)
> > > > M tabs/MainMenuScene.lua (18)
> > > > M tabs/SettingsScene.lua (8)
> > > > M tabs/StoreScene.lua (65)
> > > > M tabs/TutorialLevelDifficultyScene.lua (2)
> > > > M tabs/TutorialMainGameRightScene.lua (22)
> > > > M tabs/TutorialMainGameScene.lua (60)
> > > > A tabs/TutorialMainGameWrongScene.lua (44)
> > > > M tabs/TutorialMainMenuScene.lua (10)
> > > > A tabs/TutorialOverScene.lua (39)
> > > > M tabs/WorldsScene.lua (6)
> > > > Patch Links:
> > > >
> > > > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7.patch
> > > > https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7.diff
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7#issuecomment-170274879
> >
> > > .
> > >
> >
> > --
> > *ocsb.ca
> > <
> http://ocsb.ca/?utm_source=ocsbstudents&utm_medium=email_footer&utm_campaign=awareness>
> *
> > | *Inspired education. Inspiring students.*
> >
> > Think "green," please consider the environment before printing this
> email.
> >
> >
> > *Confidentiality and privacy notice: This email, including any
> attachments,
> > is for the sole use of the intended recipient(s) and may contain
> > confidential and privileged information. Any unauthorized review, use,
> > disclosure, or distribution is prohibited. If you received this email
> > and are not the intended recipient, please inform the sender by email
> reply
> > and destroy all copies of the original message. This email and any
> > emails sent to or from the Ottawa Catholic School Board may be
> > transmitted or stored outside of Canada. *
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MotherTeresaHS/FinalAppGroup2-2015/pull/7#issuecomment-170293414>
> .
>

-- 
*ocsb.ca 
<http://ocsb.ca/?utm_source=ocsbstudents&utm_medium=email_footer&utm_campaign=awareness> *
| *Inspired education. Inspiring students.* 

Think "green," please consider the environment before printing this email.


*Confidentiality and privacy notice: This email, including any attachments, 
is for the sole use of the intended recipient(s) and may contain 
confidential and privileged information. Any unauthorized review, use, 
disclosure, or distribution is prohibited. If you received this email 
and are not the intended recipient, please inform the sender by email reply 
and destroy all copies of the original message. This email and any 
emails sent to or from the Ottawa Catholic School Board may be 
transmitted or stored outside of Canada. *

**Comment by Mr-Coxall** [comment]
Great.
Thanks

**Pull request merged**
